config/routes.rb
Rails.application.routes.draw do

  root to: 'ingredients#index'

  get '/signup' => 'users#new'
  post '/user' => 'users#create'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :users
  resources :ingredients
  resources :employees

end

app/models/employee.rb
class Employee
  include Mongoid::Document
  field :name, type: String
  field :hourly_wage, type: Float
  field :address, type: String
end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  field :name, type: String
  field :quantity, type: Float
  field :units, type: String
  field :price_per_unit, type: Integer
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_secure_password #tells rails to have a password_digest

  validates :email, uniqueness: true 
  validates :password, confirmation: true #standard for WDI not in real world
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #helper method
  def current_user
    @current_user ||= User.find(session[:user_id]["$oid"]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authorize

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

private

  def employee_params
    params.require(:employee).permit(:name, :hourly_wage, :address)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    current_user
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render :edit
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    
    @ingredient.destroy
    
    redirect_to ingredients_path
  end

private

  def ingredient_params
    params.require(:ingredient).permit(:name, :units, :price_per_unit, :quantity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end
  
  def create #creates login session
    user = User.find_by(email: params[:user][:email])#authenticate
    
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id  #adds cookie
      redirect_to employees_path
    else
      render :new
    end
  end

  def destroy #ends logout session
    session[:user_id] = nil
    redirect_to '/login'
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create  
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation))
    
    if @user.save
      redirect_to employees_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/edit.html.erb
<%= form_for @employee do |f| %>
  Name: <%= f.text_field :name %><br>
  Hourly Wage (float): <%= f.number_field :hourly_wage, :step => 0.01 %><br>
  Address: <%= f.text_field :address %><br>
  <%= f.submit 'Add Employee' %><br>
<% end %>

app/views/employees/index.html.erb
<h4><%= link_to 'Add Employee', new_employee_path %></h4>

<table>

  <thead>
    <th>Name</th>
    <th>Hourly Wage</th>
    <th>Address</th>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= number_to_currency(employee.hourly_wage) %></td>
        <td><%= employee.address %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/employees/new.html.erb
<%= form_for @employee do |f| %>
  Name: <%= f.text_field :name %><br>
  Hourly Wage (float): <%= f.number_field :hourly_wage, :step => 0.01 %><br>
  Address: <%= f.text_field :address %><br>
  <%= f.submit 'Add Employee' %><br>
<% end %>

app/views/ingredients/edit.html.erb
<%= form_for @ingredient do |f| %>

  Name: <%= f.text_field :name %><br>
  Initial Quantity (float): <%= f.number_field :quantity, :step => 0.01 %><br>
  Units (plural): <%= f.text_field :units %><br>
  Unit Price (cents): <%= f.number_field :price_per_unit %><br>
  <%= f.submit 'Save Changes' %>
  
<% end %>

app/views/ingredients/index.html.erb
<h4><%= link_to 'Add New Ingredient', new_ingredient_path %></h4>

<table>

  <thead>
    <th>Name</th>
    <th>Quanitity</th>
    <th>Unit Price</th>
  </thead>

  <tbody>
    <% @ingredients.each do |i| %>
      <tr>
        <td><%= i.name.downcase %></td>
        <td><%= i.quantity %> <%= i.units %></td>
        <td>$<%= i.price_per_unit / 100 %>.<%= i.price_per_unit % 100 %> per <%= i.units.singularize %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(i) %> | <%= link_to 'X', i, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/ingredients/new.html.erb
<%= form_for @ingredient do |f| %>
  
  Name: <%= f.text_field :name %><br>
  Initial Quantity (float): <%= f.number_field :quantity, :step => 0.01 %><br>
  Units (plural): <%= f.text_field :units %><br>
  Unit Price (cents): <%= f.number_field :price_per_unit %><br>
  <%= f.submit 'Create Ingredient' %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saladly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  You are signed in as <%= current_user.email %> | <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to "Login", logout_path %> | <%= link_to "Signup", signup_path %>
<% end %>



<h1>Saladly</h1>
The Salad Makers Friend!

<h3><%= link_to 'Ingredients', ingredients_path %> | <%= link_to 'Employees', employees_path %></h3>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Welcome to Saladly!</h1>

<%= form_for @user do |f| %>

  First Name: <%= f.text_field :first_name %>
  Last Name: <%= f.text_field :last_name %>
  Email: <%= f.text_field :email%>
  Password: <%= f.password_field :password %><br>
  Please confirm your pasword <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Signup" %><br>

<% end %>